<?php

namespace AppBundle\DataFixtures;

use AppBundle\Entity\Post;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Validator\Constraints\DateTime;

class bPostFixtures extends Fixture
{
	public function load(ObjectManager $manager)
	{		
		$titles = array('title1', 'title2', 'title3', 'title4', 'title5');
		$texts = array('text_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_text1', 'text_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_text2', 'text_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_text3', 'text_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_text4', 'text_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_texttext_text_text5');

		for ($i = 0; $i < 10; $i++) {	
			$randCategoryId = mt_rand(1, 5);
			$post = new Post();
			$post->setTitle($titles[array_rand($titles)]);
			$post->setText($texts[array_rand($texts)]);
			$post->setCategoryId($this->getReference('category_number'.$randCategoryId));
			$post->setPostedDate(new \DateTime(date('Y-m-d')));
			$post->setUpdatedDate(new \DateTime(date('Y-m-d')));

			$manager->persist($post);			
		}

		$manager->flush();
	}
}